### ISSUE TITLE
T450 Wifi replacement problem

### ISSUE THREAD

**Issue by samondlee** [jsassu20/Lenovo-ThinkPad-T450-macOS-Catalina#32]
Hi,jsassu20,

thanks for your hardwork on EFI for T450....

there is a problem after i change my wifi to bcm94360CSAX ,i can use wifi in MACos

but when i return to win10, i can find the wifi device working,but it can't find any wifi signal....

i ve reinstall several version drivers of it....also reinstalled win10 for several times,but i dont know why it still can find any wifi signals...

Is there still any Lenovo FRU authentication on t450 bios?

Oh,btw my T450 has geforce 940m on it....

**Comment by jsassu20** [comment]
No its been disabled did you try the windows drivers in my utilities folder?

**Comment by samondlee** [comment]
![321](https://user-images.githubusercontent.com/8521327/69683061-6a4e5200-10ee-11ea-8666-bb432cfa37e9.PNG)
![dasd](https://user-images.githubusercontent.com/8521327/69683062-6ae6e880-10ee-11ea-86bc-0b6647e874eb.jpg)
![捕获](https://user-images.githubusercontent.com/8521327/69683063-6ae6e880-10ee-11ea-9834-b4954a3f917a.PNG)
yeah，i reinstalled the drivers ,the device BCM94360CSAX is working ,but still cant find any wifi signals...

and i try to installed different Wlan card before,such as BCM94360CS2 still this problem,It can be used in mac but still can‘t find signals in windows

**Comment by jsassu20** [comment]
I found working drivers for both

**Comment by jsassu20** [comment]
https://github.com/jsassu20/Apple-Airport-Broadcom-BCM4360-Windows-Drivers

> ![321](https://user-images.githubusercontent.com/8521327/69683061-6a4e5200-10ee-11ea-8666-bb432cfa37e9.PNG)
> ![dasd](https://user-images.githubusercontent.com/8521327/69683062-6ae6e880-10ee-11ea-86bc-0b6647e874eb.jpg)
> ![捕获](https://user-images.githubusercontent.com/8521327/69683063-6ae6e880-10ee-11ea-9834-b4954a3f917a.PNG)
> yeah，i reinstalled the drivers ,the device BCM94360CSAX is working ,but still cant find any wifi signals...
> 
> and i try to installed different Wlan card before,such as BCM94360CS2 still this problem,It can be used in mac but still can‘t find signals in windows

Sorry for late response here you go, I can verify that these drivers work for both cards as Ive tested myself .

https://github.com/jsassu20/Apple-Airport-Broadcom-BCM4360-Windows-Drivers

**Comment by jsassu20** [comment]
I would also make sure there are no shorts on the card due to possible short to ground from the screw that holds the adapter in place this is a very common issue Ive had numerous people contact me with issues that have been different in actual experiences which have been directly attributed to this exact situation. Ensure there is a sufficient substance between the adapter and back of wifi card which can ensure no short is occurring.

**Comment by karlamba** [comment]
Hi jsassu20,
My problem is related with WIFI replacement so I will write it here even if it is an different kind than above one. I've bought the same recommended by you WIFI card and adapter:
- https://www.amazon.com/dp/B00PDN4H9E/ref=cm_sw_r_cp_api_i_Yu7LDbEA8CT4Z
- https://www.amazon.com/dp/B01KHRJVXW/ref=cm_sw_r_cp_api_i_2o7LDbKZP042Q

I have T450 so the same as you did this hackintosh build. Now I've tried to put these new wifi and adapter into it and it works very well except the thing that there is too little space to put the cover of the laptop back in place without some deformation of it. How did you "fix" that or did you use other way to eliminate the cover deformation?

Cheers!

**Comment by jsassu20** [comment]
I cut the adapter to the lowest point I could and didn’t use any screws I just electrical taped the adapter and card and installed in the slot the card won’t go anywhere

**Comment by jsassu20** [comment]
That adapter might work better I’m not sure though I haven’t tried myself

**Comment by AgentHV** [comment]
So I fixed this by updating the specific driver by using driver booster. I know, everybody hates driver booster but I couldn’t find the right driver in anywhere else. Windows shows me them as 2015 drivers while the working one seems to be a 2017 driver.

**Comment by karlamba** [comment]
@jsassu20 - and it really don't make any deformation on the laptop cover in this case? I will try out this too as I'm still waiting for this second different adapter. 

Is it cut like this?
![image](https://user-images.githubusercontent.com/61464592/75622581-39c0fd00-5ba2-11ea-9b57-8cea29d06f08.png)

**Comment by AgentHV** [comment]
I have the same exact same adapter, even in 450s. This should work if you cut it, although I haven’t even noticed a deformation without cutting it.

**Comment by karlamba** [comment]
Did you Guys remove this so the wifi card is much closer to the adapter? Is it the only way?

![image](https://user-images.githubusercontent.com/61464592/75624394-038c7900-5bb4-11ea-91ee-1b5b564d5a7f.png)

**Comment by AgentHV** [comment]
Your can remove the both upper holes for the screws with a simple screwdriver. That makes it a little bit thinner. I wouldn't remove the rubber, I think it is there to prevent shortening the card. Try to close it, in my case it looked the same and worked. If its too thick do not remove everything from that rubber, just make it thinner to not damage the card.

**Comment by karlamba** [comment]
@AgentHV - thx for tip - what about that part (I'm not sure which holes you are talking about).
_You can remove both upper holes for the screws with a simple screwdriver._

**Comment by AgentHV** [comment]
![75622581-39c0fd00-5ba2-11ea-9b57-8cea29d06f08](https://user-images.githubusercontent.com/39234676/75624720-15235000-5bb7-11ea-807b-80088ed6d368.jpeg)
I remember these both holes being for screws that arent needed and having a piece of metal in them which makes them a little bit higher. You can get this piece out with a screwdriver or just cut this part.

**Comment by karlamba** [comment]
It's much better now but anyway dome little deformation of the case cover is noticeable.
Hmm maybe its so small that you don't see it in normal use ;) - it is visible when laptop stands on the table and you will look up on here:

![image](https://user-images.githubusercontent.com/61464592/75625312-46068380-5bbd-11ea-9299-6cc808be299a.png)

I will use it like this for now - will test the other adapter when he arrives (around March 6).

**Comment by karlamba** [comment]
Gents - I did a big mistake as I've ordered the following another adapter:
https://www.amazon.com/NGFF-Mini-PCI-Adapter-Cable/dp/B07JFYSNVL/ref=pd_sbs_147_2/136-2423406-3935226?_encoding=UTF8&pd_rd_i=B07JFYSNVL&pd_rd_r=16600851-9165-4460-9c4f-16ee38e1abb8&pd_rd_w=cW78c&pd_rd_wg=xlfcn&pf_rd_p=7cd8f929-4345-4bf2-a554-7d7588b3dd5f&pf_rd_r=2F4RG1SZJX6KAKY7MXDN&psc=1&refRID=2F4RG1SZJX6KAKY7MXDN

Unfortunately it is not valid for this wifi card because it is for Mini PCI-E wifi cards...
Do you know any similar adapters which will be good for this?

**Comment by svobluk** [comment]
> Gents - I did a big mistake as I've ordered the following another adapter:
> https://www.amazon.com/NGFF-Mini-PCI-Adapter-Cable/dp/B07JFYSNVL/ref=pd_sbs_147_2/136-2423406-3935226?_encoding=UTF8&pd_rd_i=B07JFYSNVL&pd_rd_r=16600851-9165-4460-9c4f-16ee38e1abb8&pd_rd_w=cW78c&pd_rd_wg=xlfcn&pf_rd_p=7cd8f929-4345-4bf2-a554-7d7588b3dd5f&pf_rd_r=2F4RG1SZJX6KAKY7MXDN&psc=1&refRID=2F4RG1SZJX6KAKY7MXDN
> 
> Unfortunately it is not valid for this wifi card because it is for Mini PCI-E wifi cards...
> Do you know any similar adapters which will be good for this?

I did excatly same mistake last time...

You need to order something like this: https://a.aliexpress.com/_dTNsW4f

**Comment by karlamba** [comment]
@svobluk - thx man!

Question to those who use the standard adapter: Did you remove this "screw holder"? I still don't get it how in your T450's you don't have any deformation of the case cover.

![image](https://user-images.githubusercontent.com/61464592/75795845-29ac4780-5d73-11ea-8841-b863fea9958e.png)

**Comment by jsassu20** [comment]
You want an ngff adapter with the A+E key configuration. M.2 (NGFF) ports have multiple key configurations for different purposes. The Airport card is made up of a WiFi chip and a Bluetooth chip. The WiFi portion of the card runs off of PCIe lanes and the Bluetooth utilizes an internal USB hub that’s specifically routed to the M.2 slot for the WiFi card. The A+E key provides the proper access for usb

**Comment by jsassu20** [comment]
> @svobluk - thx man!
> 
> Question to those who use the standard adapter: Did you remove this "screw holder"? I still don't get it how in your T450's you don't have any deformation of the case cover.
> 
> ![image](https://user-images.githubusercontent.com/61464592/75795845-29ac4780-5d73-11ea-8841-b863fea9958e.png)

You can also mold the rubber on the back of the airport card to flatten it out and give you extra space just slowyly push and stretch it so it flattens of and gives you extra space

**Comment by svobluk** [comment]
> @svobluk - thx man!
> 
> Question to those who use the standard adapter: Did you remove this "screw holder"? I still don't get it how in your T450's you don't have any deformation of the case cover.
> 
> ![image](https://user-images.githubusercontent.com/61464592/75795845-29ac4780-5d73-11ea-8841-b863fea9958e.png)

I have slightly visible deformantion of the backcover as well. In my case I would rather say because of the heat from the card since I was able to attach the case without any deformation in that time but after some time I can see small deformation there, even more noticable by hand.

**Comment by karlamba** [comment]
Guys I have another request - I've just installed win10 and used the drivers you suggested here but no any wifi network I can find. I don't think it is an issue of the wifi card connection etc. In MACOS everything works fine but in win10 I can't find any wifi networks even if not any issues found in the device manager.

**Comment by AgentHV** [comment]
For me, the Driver-Booster-Driver worked even tough any other driver didn't. Just install any of the recommended drivers and then download driver booster and the specific driver via ethernet.

**Comment by karlamba** [comment]
hmm... I've tried it now and it didn't change anything. The problem exist. Now I only think that maybe this is a problem with my antena connection. Is it possible that in windows this could be the problem if in MACOS everything works fine?

I've connected the wifi antennas to the "green" and to the red I've connected 1 "mobile" antenna.

![image](https://user-images.githubusercontent.com/61464592/76170463-649ee880-6182-11ea-87c9-85c669406e54.png)

**Comment by AgentHV** [comment]
I had it the other way around but this shouldn’t change anything. Having the card recognized but not seeing any networks is that classic driver error. You may try to install and update different drivers until it works. Aaaaaaaand have you tried to turn it on and off again?

**Comment by karlamba** [comment]
I've tried to disable/enable wifi device in windows device manager. Tried to reinstall different wifi drivers etc. Did you use exactly drivers specified by @jsassu20  and can you tell me please how you have connected antennas?

**Comment by AgentHV** [comment]
I tried every driver from the thread and then got the windows drivers in macOS via the bootcamp-assistant and tried them too. I can’t say which one worked for me but I had to remove one, restart, install one, restart. There are around 4 different drivers, just try all of them until one gets recognized by driver booster.

**Comment by karlamba** [comment]
ok I will try but can't you just give me at least the version number of drivers you use in win10? And what do you mean "until one gets recognized by driver booster"? I did that and my wifi drivers were updated by it - still without success.

**Comment by karlamba** [comment]
Guys, can you please let me know which Win10 build you use? Is it 1903 or 1909? My wifi under win10 still doesn't work. Can you also let me know which driver version you have working for you?

**Comment by gabgabe** [comment]
Hi all thinkpad mates.
I’m a little confused, can someone please explain the mind of stuff we need to replace?

I have installed a M.2 SSD that i’d use for OS + sata SSD for encrypted storage.

Well I have to replace existing wifi card ok, but is ”BCM94360CSAX“ size bigger? do I have to remove my os ssd to put new wifi card? Where goes the adaptor? >_<

Im confused on different types of hardware, adaptors ecc. please help me understanding them :( 
Also antennas where do you plug them?

Thank you! I will post photos and share all at job done

**Comment by karlamba** [comment]
Just check my foto as it is also above - you can see the BCM94360CSAX used with the adapter - all is working in the same wifi port as the old "original" wifi card.

![image](https://user-images.githubusercontent.com/61464592/76758585-46407a80-678a-11ea-8940-e841c525d696.png)

**Comment by gabgabe** [comment]
I have a question
My T450 has UEFI bios version 1.37
Is there any whitelish or other troubles of compatibility replacing to BCM9436CSAX?
Do I have to reflash bios chip?
Thank you

**Comment by karlamba** [comment]
It should not be. But can't you just in problems downgrade to bios v 1.35? I see an option in the bios which allows to do downgrade.

**Comment by svobluk** [comment]
> Just check my foto as it is also above - you can see the BCM94360CSAX used with the adapter - all is working in the same wifi port as the old "original" wifi card.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/61464592/76758585-46407a80-678a-11ea-8940-e841c525d696.png)
> 
> 
> 
> BTW - I still have problem with this card in win10 but maybe this is because of the win10 newest build 1909 - can someone confirm this that you use older win10 builds?

I have 1903 release with the same card now and I have excatly the same behavior - Wifi is visible inside the system but with no networks around

I have tested DriverPack / DriveBooster / BootCamp drivers but no luck.... still looking for the working one.

Bluetooth works fine with the driver from the BootCamp.

( previously I used **BCM943602CS** which is fully working inside W10.... but I have moved that card to the T480 hack )

**Comment by karlamba** [comment]
I've also tested 1909 release last time - fresh win10 install just to see if any of these posted win10 wifi drivers will work (even I've used Driver Booster as suggested before) - NO success. 

So I'm still confused how can it work for few Guys from here and for us it doesn't.

@jsassu20 , @AgentHV - are you able to help us? can you check your win10 release build and wifi drivers version? also it would be helpful if you could maybe tell us how did you install these drivers (I mean from the .exe file or fully manually by selecting .inf file)?

**Comment by karlamba** [comment]
@AgentHV - now I've figure out that you have mentioned before that Driver Booster has found for you the correct driver which is from 2017. For me Driver Booster found the driver only from 2016 and I don't know why I cannot update to 2017 driver. Which Diver Booster version do you have?

**Comment by svobluk** [comment]
> @AgentHV - now I've figure out that you have mentioned before that Driver Booster has found for you the correct driver which is from 2017. For me Driver Booster found the driver only from 2016 and I don't know why I cannot update to 2017 driver. Which Diver Booster version do you have? 

same here, the last Driver Booster offers is from 2016

**Comment by AgentHV** [comment]
First, my windows 10-Version is 1909, so it may be a 1903-error.
For strange reasons, driver booster won't show the card as an airport card, it shows it as:
![AirportCard](https://user-images.githubusercontent.com/39234676/77408210-a8673400-6db7-11ea-876c-d368d4bc726c.PNG)
The driver-details which are shown in the device manager are:
![DriverDetailst](https://user-images.githubusercontent.com/39234676/77408467-0d228e80-6db8-11ea-92b0-32dd2e5a0bc7.PNG)
In the end, I should mention that I've turned off energy saving in the device manager too, maybe that helped as it does with many driver-related problems.

**Comment by karlamba** [comment]
ahaaaa... so it is completely different driver then - I will try it today.

Maybe you have the drivers you have installed and which were after then replaced by Driver Booster?

**Comment by svobluk** [comment]
Hi, I just tested exactly the same driver as stated on the screen and I have exactly the same issue as @karlamba.

I think we are talking about different cards. May we all check the hardware IDs from device manager??

Mine is:
PCI\VEN_14E4&DEV_43A0&SUBSYS_0112106B&REV3

**Comment by AgentHV** [comment]
Mine is PCI\VEN_14E4&DEV_43BA&SUBSYS_0133106B&REV_01
so it differs after the 43. First letters should be the vendor but the following are differing after just a few digits, maybe we have a card from the same series but not the same model.
Strange, eBay and the packaging are telling me that its an BCM94360CSAX 🤔

**Comment by karlamba** [comment]
@jsassu20 - do you have the same model? I think you have the one we have with @svobluk 
Can you please let us know and maybe share your driver version etc?

**Comment by svobluk** [comment]
> Mine is PCI\VEN_14E4&DEV_43BA&SUBSYS_0133106B&REV_01
> 
> so it differs after the 43. First letters should be the vendor but the following are differing after just a few digits, maybe we have a card from the same series but not the same model.
> 
> Strange, eBay and the packaging are telling me that its an BCM94360CSAX 🤔 
> 
> 

Don’t you have BCM94360**2**CSAX?

**Comment by AgentHV** [comment]
So the card-body itself tells me it’s a BCM943602CS... I don’t know who I can trust but the seller told me he pulled it from a working system, so he may just have written the wrong number into his eBay-system. In both cases, it isn't the same card as the one that you have, either way the AX or the 2 are missing.

**Comment by svobluk** [comment]
> So the card-body itself tells me it’s a BCM943602CS... I don’t know who I can trust but the seller told me he pulled it from a working system, so he may just have written the wrong number into his eBay-system. In both cases, it isn't the same card as the one that you have, either way, the AX or the 2 are missing.

Thanks for confirmation. Yes, **BCM943602CS** works under the WIN10 - I have this card in my T480 hack.... Hmm wanted to try something different now as this card was cheaper and seems it was not a good choice.

**Comment by karlamba** [comment]
I think only @jsassu20 can confirm this (if and how it works in win10) and do for us the last check as he mentioned in his/this github that it works - even he provided win10 drivers but somehow they don't work for us.

**Comment by svobluk** [comment]
@karlamba That’s correct. I used BCM943602CS with T450 and now I have moved that card into T480.

Confirmed with Mojave / Catalina and WIN10 as well.

**Comment by gabgabe** [comment]
NO IT DOES NOT FIT T450 OK!!!
You better desolder the female screw on pc mainboard

Got my laptop suddenly fried 

![7C59174A-34CF-4985-A419-9B8200926F61](https://user-images.githubusercontent.com/45693996/78423803-43d68f80-7669-11ea-86ea-6a8c541c80ad.jpeg)

**Comment by AgentHV** [comment]
Sorry to hear that, hope there’s not too much damage done. Which screw should be desoldered? Will electrical tape do this? And which card do you have?

**Comment by gabgabe** [comment]
That’s the story:
Arrived the card and adapter I put them and test, working, I close pc
Reboot, no wifi.
Open pc, remove and reinstall card. Test, working, close pc.
Reboot, working.
After a while of working wifi, system starts lagging, then i notice there is not wifi. 
Reboot
Working
At the end of the day again no wifi
Reboot
Working



This morning again no wifi,
Reboot no wifi, reboot no wifi, okay i decide to open again the pc so I backflip it on table, remove battery, re backflip, turn on for entering in bios and disable builtin battery. 

Enter in bios, then the coffe is ready so I switch off the gas (exactly 10 seconds of distraction) when I come back to pc I smell the smoke and immediately got panic shutting down holding power button.

 Too late.

I dont know if it was a bad contact on wifi card-adapter or adapter-pcb
They all got fried. 

Just cleaned the contacts on pcb with a needle (they got melted in the plastic) now i can see copper contact of The 3 pins but seems to be at lower level than the others, so I hope they can close the contacts with the card.

Just tested with old wifi card and seems to work but I don’t know if there are other 3v3 pins that old wifi card use instead of the burned because the adapter should use only pin 2 and 3 (or 1&3 i dont remember)

I cant find broadcom wifi pinout, melted the first 2 pins on the left, they should be 3v3 and GND, then the wifi card should be ok as the short was not inside the card.

I don’t know if it was a faulty adapter or card pins, that’s frustrating.
How did you do guys?
I attach the first attempt when I installed it

![ED1A0CE4-DC30-4E23-8537-D77F86EDF8A3](https://user-images.githubusercontent.com/45693996/78434339-4c819280-7676-11ea-83a8-7c395b05fd88.jpeg)

There is that female screw and these two diodes that doesn’t let the card go lower and occupy less space
![D6BA7623-2545-461F-A3AA-5A284509BC47](https://user-images.githubusercontent.com/45693996/78434402-51dedd00-7676-11ea-84c1-658cee4e53f3.jpeg)
![B1D9AFB4-CB13-471C-B663-100F7383DF0A](https://user-images.githubusercontent.com/45693996/78434415-52777380-7676-11ea-8aa1-242bf3206ccb.jpeg)


Hope to be useful

**Comment by svobluk** [comment]
Sorry to hear, but I do not see any card “protection” on the photo. So the card most probably touched the screw and short circuited.

Normally the card has a protection from the factory, if not it must be added to protect against short circuit, especially in our case since we use additional adapter bellow with that screw.

![image](https://user-images.githubusercontent.com/36888336/78450327-19db9800-767e-11ea-8e36-752ef409fd92.jpeg)

See the picture. I recommend cover more than as it comes from the factory. Like the red square.

![image](https://user-images.githubusercontent.com/36888336/78450504-43e18a00-767f-11ea-9b1d-d087c45bb98f.jpeg)

**Comment by gabgabe** [comment]
Of course I covered the screw, wifi card was not shorting anything, the short is on the pins, the card circuit seems to be ok...
I think it was not well fixed in the adapter and probability shorted because of the micro movements while handling laptop

**Comment by svobluk** [comment]
At the very beginning, I had the exact same problems you described - after the while wifi card and whole bottom of the laptop started to be very hot and the macOS stopped to be responsive, CPU was 100% utilised, no wifi, the problems remained even after the reboot.

I was wondering what the hack and I have found that the culprit is the wifi card or the adapter underneath.

1. I have added thermal pad / protection to the whole bottom of the card so no circuit shortages between the wifi card, the adapter or screw could happen. 
2. Please make sure that the adapter is correctly inserted and screwed in.
3. Please make sure that the wifi card is correctly inserted to the adapter and that your wifi card is **parallel** with the adapter. This is quite an important. I think this was the problem in my case.

![final (kopie)](https://user-images.githubusercontent.com/36888336/78452521-f4ee2180-768b-11ea-973c-32a37cc9861f.jpg)

Hopefully it helps.

**Comment by karlamba** [comment]
well Guys really sorry to hear your problems. I didn't had so. I have only problem with win10 wifi drivers. I don't use any screw and I have covered the bottom of the wifi card with termopad so it is safed from any contact with the adapter. I also didn't see any problems if wifi card is (or not) parallel - in fact I don't use any screws so it is just "taped" - the adapter is taped and the card is just inserted. No any problems under MAC OS at all since the beginning ( 1 or 2 monts). Thx Guys for your experience as all is very important as it can help many people.

Cheers and be healthy!

**Comment by jsassu20** [comment]
> I think only @jsassu20 can confirm this (if and how it works in win10) and do for us the last check as he mentioned in his/this github that it works - even he provided win10 drivers but somehow they don't work for us.
> 
> @svobluk - so you can confirm that below card should work without issues both in hackintosh and win10?
> https://www.ebay.pl/itm/Apple-Macbook-Pro-A1502-13-A1398-15-Wireless-WiFi-Card-653-0194-BCM943602CS/352585042098?hash=item5217b4c8b2:g:~zQAAOSw7tRee4LO
> 
> @jsassu20 - can you please confirm which exactly model you have and which drivers you use in win10?

Broadcom BCM94360CS, BCM94360CS2, BCM94360CSAX, BCM94360CD

are all supported Apple branded cards which need adapter.

https://www.amazon.com/Hackintosh-M-2-NGFF-BCM94360NG-Continuity/dp/B083YXS7VF/ref=sr_1_2?dchild=1&keywords=Hackintosher+ngff&qid=1586218205&s=electronics&sr=1-2-spell

is a native ngff card that works OOB like native apple cards but costs more.

**Comment by karlamba** [comment]
OK but we have BCM94360CSAX and it doesn't work in win10. Can you check please which exactly driver version you use in win10?

**Comment by jsassu20** [comment]
I know which version you you're talking about.

I've used both the stock Bootcamp drivers and the specific ones in my repo with the BCM94360CS, BCM94360CS2, BCM94360CSAX, BCM94360CD, and BCM94322 equivalent hardware and the all work fine in windows 7-10 each time I've installed the drivers. Have you tried disabling driver signature enforcement?

**Comment by karlamba** [comment]
@jsassu20 - yes and it doesn't work at all in even earlier win10 builds. If you could help and for example check exactly version of win10 wifi drivers you use then it would be helpful. Maybe you have the drivers which you use so we can check them?

well... I've just bought BCM943602CS, just installed and I didn't have to do anything with drivers... It just work both in win10 and MACOS without any "tricks"... I really don't know but maybe "AX" version is somehow different and some of them works and some other don't work in win10? I don't know...

**Comment by roibudoru** [comment]
> @jsassu20 - yes and it doesn't work at all in even earlier win10 builds. If you could help and for example check exactly version of win10 wifi drivers you use then it would be helpful. Maybe you have the drivers which you use so we can check them?
> 
> well... I've just bought BCM943602CS, just installed and I didn't have to do anything with drivers... It just work both in win10 and MACOS without any "tricks"... I really don't know but maybe "AX" version is somehow different and some of them works and some other don't work in win10? I don't know...

I can also confirm this, i had the same issue..the only fix was to buy the BCM943602CS

**Comment by zzhang39** [comment]
for BCM94360CSAX, can anyone please confirm if below connection for the wire is correct?
the original wifi adapter only got two wires. there is a extra blue wire stand along(not in use).
now BCM94360CSAX has 3 spot to connect wire (J0,J1,J2).

![image](https://user-images.githubusercontent.com/15820915/92828321-e6c1d100-f3a0-11ea-9bc3-82efd7151f16.png)

**Comment by jsassu20** [comment]
> > I think only @jsassu20 can confirm this (if and how it works in win10) and do for us the last check as he mentioned in his/this github that it works - even he provided win10 drivers but somehow they don't work for us.
> > @svobluk - so you can confirm that below card should work without issues both in hackintosh and win10?
> > https://www.ebay.pl/itm/Apple-Macbook-Pro-A1502-13-A1398-15-Wireless-WiFi-Card-653-0194-BCM943602CS/352585042098?hash=item5217b4c8b2:g:~zQAAOSw7tRee4LO
> > @jsassu20 - can you please confirm which exactly model you have and which drivers you use in win10?
> 
> Broadcom BCM94360CS, BCM94360CS2, BCM94360CSAX, BCM94360CD ***CS2 version is a smaller form factor which is used in MacBook Air devices A1466
> 
> are all supported Apple branded cards which need adapter.
> 
> https://www.amazon.com/Hackintosh-M-2-NGFF-BCM94360NG-Continuity/dp/B083YXS7VF/ref=sr_1_2?dchild=1&keywords=Hackintosher+ngff&qid=1586218205&s=electronics&sr=1-2-spell
> 
> is a native ngff card that works OOB like native apple cards but costs more.

Hi yes I can confirm the following cards work 

Broadcom BCM94360CS (with NGFF A/e adapter)  

Broadcom BCM 94360CS2 AC (with NGFF A/e adapter) 

Broadcom BCM94360CSX AC (with NGFF A/e adapter) 

Broadcom BCM94360CD AC (with NGFF A/e adapter) 

Broadcom BCM94331CSAX WIRELESS N Based (with ngff a/e adapter) 

Broadcom BCM94331CSDAX Wireless N Based (with ngff a/e adapter) 

Broadcom BCM94352HMB AC Mini PCIE Based (with mini-pcie to ngff a/e adapter) can be found here: 

https://www.amazon.com/Adapter-BCM94331-BCM94360CD-Converter-Windows/dp/B082X7ZSKS  

Broadcom BCM94352Z (works with no adapter needed as its NGFF A/E based and works OOB with Mac OS Mojave and Newer (may work with older versions but I can't confirm as I have not tried) can be purchased here: 

https://www.amazon.com/REKONG-BCM94352Z-802-11AC-Hackintosh-Bluetooth/dp/B0861TV873/ref=sr_1_5?dchild=1&keywords=hackintosh&qid=1599789999&s=electronics&sr=1-5

If you're having issues use the BCM94352Z it did not exist at the time I wrote the guide but it'll work just like standard Airport cards as it was directly created for use in Hackintosh machines

**Comment by Newtonjobs** [comment]
thinks发自我的华为手机-------- 原始邮件 --------发件人： James Anthony Sassu <notifications@github.com>日期： 2020年9月11日周五 10:19收件人： jsassu20/Lenovo-ThinkPad-T450-macOS-Catalina <Lenovo-ThinkPad-T450-macOS-Catalina@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [jsassu20/Lenovo-ThinkPad-T450-macOS-Catalina] T450 Wifi replacement problem (#32)


I think only @jsassu20 can confirm this (if and how it works in win10) and do for us the last check as he mentioned in his/this github that it works - even he provided win10 drivers but somehow they don't work for us.
@svobluk - so you can confirm that below card should work without issues both in hackintosh and win10?
https://www.ebay.pl/itm/Apple-Macbook-Pro-A1502-13-A1398-15-Wireless-WiFi-Card-653-0194-BCM943602CS/352585042098?hash=item5217b4c8b2:g:~zQAAOSw7tRee4LO
@jsassu20 - can you please confirm which exactly model you have and which drivers you use in win10?

Broadcom BCM94360CS, BCM94360CS2, BCM94360CSAX, BCM94360CD ***CS2 version is a smaller form factor which is used in MacBook Air devices A1466
are all supported Apple branded cards which need adapter.
https://www.amazon.com/Hackintosh-M-2-NGFF-BCM94360NG-Continuity/dp/B083YXS7VF/ref=sr_1_2?dchild=1&keywords=Hackintosher+ngff&qid=1586218205&s=electronics&sr=1-2-spell
is a native ngff card that works OOB like native apple cards but costs more.

Hi yes I can confirm the following cards work
Broadcom BCM94360CS (with NGFF A/e adapter)
Broadcom BCM 94360CS2 AC (with NGFF A/e adapter)
Broadcom BCM94360CSX AC (with NGFF A/e adapter)
Broadcom BCM94360CD AC (with NGFF A/e adapter)
Broadcom BCM94331CSAX WIRELESS N Based (with ngff a/e adapter)
Broadcom BCM94331CSDAX Wireless N Based (with ngff a/e adapter)
Broadcom BCM94352HMB AC Mini PCIE Based (with mini-pcie to ngff a/e adapter) can be found here:
https://www.amazon.com/Adapter-BCM94331-BCM94360CD-Converter-Windows/dp/B082X7ZSKS
Broadcom BCM94352Z (works with no adapter needed as its NGFF A/E based and works OOB with Mac OS Mojave and Newer (may work with older versions but I can't confirm as I have not tried) can be purchased here:
https://www.amazon.com/REKONG-BCM94352Z-802-11AC-Hackintosh-Bluetooth/dp/B0861TV873/ref=sr_1_5?dchild=1&keywords=hackintosh&qid=1599789999&s=electronics&sr=1-5
If you're having issues use the BCM94352Z it did not exist at the time I wrote the guide but it'll work just like standard Airport cards as it was directly created for use in Hackintosh machines
